### ISSUE TITLE
Some ideas on resources' additions

### ISSUE THREAD

**Issue by sayakpaul** [tirthajyoti/Data-science-best-resources#1]
Hi @tirthajyoti. Kudos to you for this great compilation. 

I think the following can also be great additions to the compilation: 

- [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering/index.html) book by Max Kuhn and Kjell Johnson.
- [explanied.ai](https://explained.ai/) for resources such as Visualization of Decision Trees, GBMs etc.
- [Time Series with Siraj](https://www.kaggle.com/learn/time-series-with-siraj) compiled by Kaggle Learn.
- Kaggle Learn's course on [SQL](https://www.kaggle.com/learn/sql) as it is also focused on using BigQuery to query massive datasets. 

I am sorry if I mentioned something that is already there in the compilation.

**Comment by tirthajyoti** [comment]
Done adding these. Thanks!

**Comment by sayakpaul** [comment]
I forgot to do this as a pull request. Sorry about that. Next time, I will keep this in mind for sure.
